const vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto'),assert=require('node:assert/strict');
let store={},calls=[],enabled=true,runStatus='queued',runConclusion=null,runList=[],loseReceipt=false,lockAvailable=true;
const response=value=>({getResponseCode:()=>200,getContentText:()=>JSON.stringify(value)});
const props={getProperty:k=>store[k]??null,setProperty:(k,v)=>{store[k]=v;},deleteProperty:k=>{delete store[k];}};
const sandbox={console:{log:()=>{},error:()=>{}},Date,Number,JSON,Set,PropertiesService:{getScriptProperties:()=>props},LockService:{getScriptLock:()=>({tryLock:()=>lockAvailable,releaseLock:()=>{}})},Utilities:{Charset:{UTF_8:'utf8'},DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(alg,v)=>[...crypto.createHash('sha256').update(v).digest()],computeHmacSha256Signature:(v,k)=>[...crypto.createHmac('sha256',k).update(v).digest()],getUuid:()=>crypto.randomUUID(),base64Decode:v=>Buffer.from(v,'base64'),base64Encode:v=>Buffer.from(v).toString('base64'),newBlob:v=>({getDataAsString:()=>Buffer.from(v).toString()})},UrlFetchApp:{fetch:(url,options)=>{calls.push({url,options});assert(!/drip_sender|prospecting\.yml/.test(url));if(url.endsWith('/user'))return response({login:'operator'});if(url.includes('/contents/system_config.json'))return response({sha:'a',content:Buffer.from(JSON.stringify({email_system_enabled:enabled})).toString('base64')});if(url.includes('/workflows/auto_prospect.yml/runs'))return response({workflow_runs:runList});if(url.endsWith('/dispatches')){assert.deepEqual(JSON.parse(options.payload),{ref:'main',inputs:{force:true},return_run_details:true});if(loseReceipt)throw Error('network');return response({workflow_run_id:42});}if(url.endsWith('/runs/42'))return response({id:42,event:'workflow_dispatch',head_branch:'main',path:'.github/workflows/auto_prospect.yml',status:runStatus,conclusion:runConclusion});throw Error('Unexpected URL');}}};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync('server/apps-script/AdminRelay.gs','utf8'),sandbox);
function route(r){return JSON.parse(JSON.stringify(sandbox.adminRoute_(r)));}
function reset(){store={ADMIN_SESSION_SECRET:'test-secret',MOMENTUM_GITHUB_TOKEN:'server-only-test-token'};store.ADMIN_PASSWORD_CHECK=sandbox.adminMac_('password:'+sandbox.adminHash_('test-password'));calls=[];runList=[];enabled=true;loseReceipt=false;runStatus='queued';runConclusion=null;lockAvailable=true;}
function login(){return route({action:'login',username:'admin',password:'test-password'}).result.token;}
reset();assert.equal(route({action:'classify.start',requestId:'0'.repeat(32)}).error,'UNAUTHORIZED');assert.equal(calls.length,0);
assert.equal(route({action:'login',username:'admin',password:sandbox.adminHash_('test-password')}).error,'INVALID_LOGIN');
for(let i=0;i<8;i++)route({action:'login',username:'admin',password:'wrong'});assert.equal(route({action:'login',username:'admin',password:'test-password'}).error,'LOGIN_RATE_LIMIT');
reset();let token=login();assert(!store.ADMIN_SESSIONS.includes(token));assert(route({action:'session',session:token}).ok);assert(!JSON.stringify(route({action:'session',session:token})).includes(store.MOMENTUM_GITHUB_TOKEN));
for(const flag of [false,undefined,null,'true']){enabled=flag;assert.equal(route({action:'classify.start',session:token,requestId:crypto.randomUUID()}).error,'SYSTEM_PAUSED');}enabled=true;
let requestId=crypto.randomUUID();let result=route({action:'classify.start',session:token,requestId});assert.equal(result.result.phase,'accepted');route({action:'classify.start',session:token,requestId});assert.equal(calls.filter(c=>c.options.method==='post').length,1);
runStatus='in_progress';assert.equal(route({action:'classify.status',session:token}).result.phase,'running');runStatus='completed';runConclusion='success';assert.equal(route({action:'classify.status',session:token}).result.phase,'success');runConclusion='failure';assert.equal(route({action:'classify.status',session:token}).result.phase,'failed');
assert.equal(route({action:'settings.update',session:token,setting:'arbitrary',value:true}).error,'INVALID_REQUEST');assert.equal(route({action:'dispatch.mailer',session:token}).error,'INVALID_REQUEST');
route({action:'logout',session:token});assert.equal(route({action:'session',session:token}).error,'UNAUTHORIZED');
reset();token=login();let sessions=JSON.parse(store.ADMIN_SESSIONS);sessions[0].expiresAt=0;store.ADMIN_SESSIONS=JSON.stringify(sessions);assert.equal(route({action:'session',session:token}).error,'UNAUTHORIZED');
reset();token=login();loseReceipt=true;result=route({action:'classify.start',session:token,requestId:crypto.randomUUID()});assert.equal(result.result.phase,'unknown');route({action:'classify.start',session:token,requestId:crypto.randomUUID()});assert.equal(calls.filter(c=>c.options.method==='post').length,1);
const created_at=new Date().toISOString();runList=[{id:42,actor:{login:'operator'},created_at}];assert.equal(route({action:'classify.status',session:token}).result.runId,42);assert.equal(calls.filter(c=>c.options.method==='post').length,1);
reset();token=login();loseReceipt=true;route({action:'classify.start',session:token,requestId:crypto.randomUUID()});runList=[{id:42,actor:{login:'operator'},created_at},{id:43,actor:{login:'operator'},created_at}];assert.equal(route({action:'classify.status',session:token}).result.phase,'unknown');
lockAvailable=false;assert.equal(route({action:'classify.status',session:token}).error,'BUSY');
console.log('PASS server authentication, hash replay rejection, expiry, logout, rate limit, fail-closed switch, dispatch allowlist, idempotency, status, ambiguous response recovery, no secret response.');
