const vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto'),assert=require('node:assert/strict');
let now=Date.now(),dbText=null,store={CONSULT_HEARTBEAT:String(now)};
class Clock extends Date{static now(){return now;}}
const props={getProperty:k=>store[k]??null,setProperty:(k,v)=>store[k]=v,deleteProperty:k=>delete store[k]};
const file={getId:()=> 'private-file',getBlob:()=>({getDataAsString:()=>dbText}),setContent:v=>{dbText=v;}};
const ctx=vm.createContext({console,Date:Clock,Number,JSON,Set,PropertiesService:{getScriptProperties:()=>props},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})},Utilities:{Charset:{UTF_8:'utf8'},DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(a,v)=>[...crypto.createHash('sha256').update(v).digest()],getUuid:()=>crypto.randomUUID()},MimeType:{PLAIN_TEXT:'text/plain'},DriveApp:{createFile:(n,v)=>{dbText=v;return file;},getFileById:()=>file}});
vm.runInContext(fs.readFileSync('server/apps-script/AdminRelay.gs','utf8')+'\n'+fs.readFileSync('server/apps-script/ConsultStore.gs','utf8'),ctx);
const call=(fn,r)=>JSON.parse(JSON.stringify(ctx[fn](r)));
const a='a'.repeat(64),b='b'.repeat(64),worker=crypto.randomBytes(32).toString('hex');store.CONSULT_WORKER_HASH=crypto.createHash('sha256').update(worker).digest('hex');
assert.equal(call('consultPublic_',{action:'start',token:a}).error,'CONSULT_CONSENT_REQUIRED');
const A=call('consultPublic_',{action:'start',token:a,consent:true}).result;
const B=call('consultPublic_',{action:'start',token:b,consent:true}).result;
assert.notEqual(A.id,B.id);assert(!JSON.stringify(A).includes('hash'));
assert.equal(call('consultPublic_',{action:'start',token:a,consent:true}).result.id,A.id);
assert.equal(call('consultPublic_',{action:'poll',id:A.id,token:b}).error,'CONSULT_UNAUTHORIZED');
assert.equal(call('consultPublic_',{action:'list',id:A.id,token:a}).error,'CONSULT_INVALID_REQUEST');
const req={action:'send',id:A.id,token:a,requestId:crypto.randomUUID(),text:'촬영이 부담스러워요'};
assert.equal(call('consultPublic_',req).result.turns,1);assert.equal(call('consultPublic_',req).result.turns,1);
assert.equal(call('consultPublic_', {...req,requestId:crypto.randomUUID()}).error,'CONSULT_BUSY');
assert.equal(call('consultWorker_',{action:'claim',workerToken:a}).error,'CONSULT_UNAUTHORIZED');
const job=call('consultWorker_',{action:'claim',workerToken:worker}).result.job;
assert.equal(job.messages[0].text,req.text);
assert.equal(call('consultWorker_',{action:'complete',workerToken:worker,...job,claim:'wrong',answer:'잘못된 응답'}).error,'CONSULT_INVALID_REQUEST');
const done={action:'complete',workerToken:worker,id:job.id,requestId:job.requestId,claim:job.claim,answer:'촬영 방식을 함께 정리해요'};
assert(call('consultWorker_',done).ok);assert(call('consultWorker_',done).ok);
assert.equal(call('consultPublic_',{action:'poll',id:A.id,token:a}).result.messages.length,2);
assert.equal(call('consultPublic_',{action:'poll',id:B.id,token:b}).result.messages.length,0);
assert.equal(call('consultPublic_',{...req,requestId:crypto.randomUUID(),text:'x'.repeat(1001)}).error,'CONSULT_INVALID_REQUEST');
now+=4000;call('consultPublic_',{...req,requestId:crypto.randomUUID()});now+=121000;
assert.equal(call('consultPublic_',{action:'poll',id:A.id,token:a}).result.pending,null);
assert.equal(call('consultPublic_',{action:'start',token:'c'.repeat(64),consent:true}).error,'CONSULT_OFFLINE');
assert.equal(call('adminRoute_',{action:'consult.list',session:'bad'}).error,'UNAUTHORIZED');
now+=86400000;assert.equal(call('consultPublic_',{action:'poll',id:A.id,token:a}).error,'CONSULT_UNAUTHORIZED');
console.log('consult store: consent, isolation, replay, worker auth, timeout, expiry PASS');
